language: julia
os:
  - linux
  # - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("ConicBenchmarkUtilities")); using Coverage; Codecov.submit(process_folder())'
